#.github/workflow/goreleaser.yml
# can follow this guide: https://docs.docker.com/ci-cd/github-actions/
name: goreleaser

#  every push a new tag sample like below
#  git tag -a v1.0.2
#  git push origin v1.0.2
on:
  push:
    tags:
      - '*'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: shawnzxx/bookstore_users-api

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      # This provides a temporary environment for testing the experimental features without having to commit to it's usage.
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      # checks-out our repository under $GITHUB_WORKSPACE, so our workflow can access it
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          # Note the fetch-depth: 0 option It is required for GoReleaser to work properly.
          # Without that, GoReleaser might fail or behave incorrectly.
          fetch-depth: 0

      # use our PAT and username to log into Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # enabled the multi-platform images
      - name: Set up  QEMU
        uses: docker/setup-qemu-action@v1

      # the Builder step, the action uses BuildKit under the hood through a simple Buildx action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # set up go build env
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # refer to here: https://goreleaser.com/ci/actions/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          # Represent github token and is auto filled
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - name: Extract metadata (tages, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clear
        if: always()
        run: rm -f ${HOME}/.docker/config.json